### ISSUE TITLE
Compare with Pylatexenc

### ISSUE THREAD

**Issue by Konfekt** [humenda/utexer#3]
Vielleicht wäre ein Vergleich mit https://github.com/phfaist/pylatexenc interessant, das ähnliches bewerkstelligt, aber anscheinend keine Ligaturen ersetzt.

**Comment by humenda** [comment]
When I started uTeXer, Pylatexenc did not exist. I have used it for my use-case back then and never recherched the issue again. It is interesting that pylatexenc is based on the same Unicode data that I use so that the removal of page breaks (^l) and ligature replacement is probably implemented better in the more active project. However, I am lacking time to do so. I also didn't compare the output of both programs.
